### ISSUE TITLE
Translate your readme to English

### ISSUE THREAD

**Issue by HugoGresse** [CtripMobile/DynamicAPK#1]
I guess it's true for all project that could be usefull for anyone.

**Comment by Mtpc** [comment]
![+1](http://i.imgur.com/KabOaea.jpg)

**Comment by 601367322** [comment]
学好中文才是正解！

**Comment by kaedea** [comment]
Talk is cheap, please read the code.

**Comment by hrchen** [comment]
Already done. 
Learning Chinese maybe another workaround:-)

**Comment by HugoGresse** [comment]
thank you @hrchen !
