### ISSUE TITLE
demo-base-release.apk' as it does not exist

### ISSUE THREAD

**Issue by dxiaogang** [CtripMobile/DynamicAPK#25]
- What went wrong:
  Cannot expand ZIP '/Users/daixiaogang/github/DynamicAPK/build-outputs/demo-base-release.apk' as it does not exist.

我检查过  名字都没有问题  .

**Comment by TediWang** [comment]
In Command ：$ gradle clean  ，then $ gradle assembleRelease bundleRelease repackAll

**Comment by dxiaogang** [comment]
@TediWang   Thank you for answer my questions,but it  does not  work.

**Comment by SparkInLee** [comment]
gradle assembleRelease
gradle bundleRelease
gradle repackAll
