### ISSUE TITLE
插件 apk 访问 Android style 文件的问题

### ISSUE THREAD

**Issue by MrFuFuFu** [CtripMobile/DynamicAPK#26]
如：访问 v7 包下的 `Theme.AppCompat.Light` style 会报：`No resource found that matches the given name` 的错误，
以及ProgressBar 的  `@style/Widget.AppCompat.ProgressBar.Horizontal` 也是如此：`Error: No resource found that matches the given name (at 'style' with value '@style/Widget.AppCompat.ProgressBar.Horizontal').
` 等等。类似的访问 Android 这些资源都会报类似错误~~

注：v7 包已经导入：`'com.android.support:appcompat-v7:23.1.1'`

**Comment by TediWang** [comment]
v7包是否是在主工程中被导入。

**Comment by MrFuFuFu** [comment]
@TediWang 嗯，都尝试导入了
