### ISSUE TITLE
Error:Could not find com.android.tools.build:gradle:1.3.1.

### ISSUE THREAD

**Issue by CaMnter** [CtripMobile/DynamicAPK#29]
If don't open jcenter()

Error:Could not find com.android.tools.build:gradle:1.3.1.
Searched in the following locations:
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/android/tools/build/gradle/1.3.1/gradle-1.3.1.pom
    file:/Applications/Android Studio.app/Contents/gradle/m2repository/com/android/tools/build/gradle/1.3.1/gradle-1.3.1.jar
    http://mirrors.ibiblio.org/maven2/com/android/tools/build/gradle/1.3.1/gradle-1.3.1.pom
    http://mirrors.ibiblio.org/maven2/com/android/tools/build/gradle/1.3.1/gradle-1.3.1.jar
Required by:
    :DynamicAPK:unspecified

**Comment by TediWang** [comment]
yes， in china  we use the mirror to get the gradle.  in any way ,use the jcenter() and meven to get the gradle 1.3.1 is OK.

**Comment by zh79325** [comment]
我发现即使使用以下配置还是会有相同的错误
   repositories {
         maven { url "ctrip default maven repo "}
    }

**Comment by loamen** [comment]
同问

**Comment by CaMnter** [comment]
@don59 

``` gradle
buildscript {
    repositories {
        jcenter()
        maven { url "http://mirrors.ibiblio.org/maven2"}
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.1'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```

项目目录 build.gradle改这些

**Comment by loamen** [comment]
@CaMnter 这个文件本来就是这样的，改了开源中国的镜像也不对，看这里：https://github.com/CtripMobile/DynamicAPK/issues/51
