### ISSUE TITLE
[Error] Sample error as below

### ISSUE THREAD

**Issue by mrljdx** [CtripMobile/DynamicAPK#3]
*------------------------------------*
Ctrip Bundle on Nexus 5|armeabi-v7astarting...
*------------------------------------*
java.io.FileNotFoundException: /data/data/ctrip.android.sample/files/storage/meta: open failed: ENOENT (No such file or directory)
at libcore.io.IoBridge.open(IoBridge.java:456)
at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
at ctrip.android.bundle.framework.Framework.storeMetadata(Framework.java:159)

**Comment by TediWang** [comment]
I aslo test the Nexus 5，it work well。can you give me the android system version of your Nexus 5. Please Use the gradle assembleRelease bundleRelease repackAll to build and output apk is demo-release-final.apk. 
Thanks

**Comment by mrljdx** [comment]
thx, Use $ gradle assembleRelease bundleRelease repackAll ,then install the build-outputs folder apk , worked well .
