### ISSUE TITLE
抄袭淘宝的代码这么冠冕堂皇好么

### ISSUE THREAD

**Issue by zjutyujf** [CtripMobile/DynamicAPK#6]

**Comment by TediWang** [comment]
淘宝的各位好，看来有必要声明一下这个事情了。2014年在看了到这2篇文章：
http://log4think.com/use-apache-felix-in-android/
http://log4think.com/use-knopflerfish-in-android/
对osgi运用到手机有了新的方案，osgi是一个开源的框架，bundle也是其中之一。
Android上要解决代码的动态加载和资源的分区加载，难点就是资源怎么分区。
我们真正解决的是资源的分区，修改了aapt源码，并且我们的脚本也是耗费了大量精力去实现分包，R文件的合并，同时也实现了hotfix。我们也把这个实践开源了，其中修改过的aapt源代码和打包的gradle脚本，毫无保留的分享给大家，希望能帮助到更多的Android开发者。

**Comment by weiyihz** [comment]
你为什么这么不要脸！
