### ISSUE TITLE
atlas

### ISSUE THREAD

**Issue by imagebody** [CtripMobile/DynamicAPK#7]
我是手淘Atlas的早期作者之一，看到这些熟悉的类。我想问，这是携程的？还是携程抄手机淘宝的？要脸不？

**Comment by CtripMobile2** [comment]
不要脸了，打一架？

**Comment by zjutyujf** [comment]
其他的代码也是打架赢来的？

**Comment by imagebody** [comment]
你把人家还没开源的代码拿来这样公开，还蛮得意。
你妈妈也是这么借他人的基因造的你么？@CtripMobile2

**Comment by TediWang** [comment]
感谢手淘的各位~希望通过大家的努力，能一起进步，为国内的技术发展尽一下绵薄的力量，如果有问题可以联系我：tediwang@gmail.com

**Comment by lzyzsd** [comment]
@imagebody 我看到Atlas命名也是感觉好熟悉哈，欢迎Atlas作者出来分享
