### ISSUE TITLE
抄袭很简单，但是你知道为什么需要处理小米ui资源吗？

### ISSUE THREAD

**Issue by guoguo338** [CtripMobile/DynamicAPK#8]
//处理小米UI资源
            if (resources == null || !resources.getClass().getName().equals("android.content.res.MiuiResources")) {
                delegateResources = new DelegateResources(assetManager, resources);
            } else {
                Constructor declaredConstructor = Class.forName("android.content.res.MiuiResources").getDeclaredConstructor(new Class[]{AssetManager.class, DisplayMetrics.class, Configuration.class});
                declaredConstructor.setAccessible(true);
                delegateResources = (Resources) declaredConstructor.newInstance(new Object[]{assetManager, resources.getDisplayMetrics(), resources.getConfiguration()});
            }

**Comment by CtripMobile2** [comment]
这个问题嘛，雷布斯修改了默认的Resources，为啥这样做，构造函数改了呗

**Comment by guoguo338** [comment]
你以为真的这么简单？？

**Comment by zjutyujf** [comment]
求请教 
 if (file2.canWrite()) {
            if (isSameDir(file, file2)) {
                this.revisionLocation = FILE_PROTOCOL;
                this.bundleFile = new File(file, BUNDLE_FILE_NAME);
                file2.renameTo(this.bundleFile);
            } else {
                this.revisionLocation = FILE_PROTOCOL;
                this.bundleFile = new File(file, BUNDLE_FILE_NAME);
                APKUtil.copyInputStreamToFile(new FileInputStream(file2), this.bundleFile);
            }
        } else if (Build.HARDWARE.toLowerCase().contains("mt6592") && file2.getName().endsWith(".apk")) {

1 file2.canWrite()是什么情况下，意图是什么，
2 mt6592  软引用的根本原因是什么 

第三个 
else if (SysHacks.LexFile == null || SysHacks.LexFile.getmClass() == null) {
LexFile判断的意图，哪些版本开始不用LexFile了 

还有 BundleArchiveRevision 名字倒真巧了，osgi里面有这个名字吗 有AndroidHack么

还有 this.mExceptionArray = new AssertionArrayException("atlas hack assert failed");
atlas hack XXX，atlas什么意思，能一次改改干净么

**Comment by yhhong** [comment]
抄袭还是借鉴也好，多个声明感谢与沟通。对于普通开发者，我们还是希望该项目能快速发展。希望作者与广大开源贡献者一起努力！尤其是国人！

**Comment by TediWang** [comment]
感谢手淘的各位~希望通过大家的努力，能一起进步，为国内的技术发展尽一下绵薄的力量，如果有问题可以联系我：tediwang@gmail.com

**Comment by CtripMobile2** [comment]
那我就不理解了，感谢手淘的各位是几个意思呢？
